const lessonTitle = "大自然的秘密";

const lessonData = [
    // 正文第 1 段
    ["在", "zài", "in / at", "di / pada"],
    ["上一个", "shàng yí gè", "last / previous", "yang lepas / terdahulu"],
    ["假期", "jià qī", "vacation / holiday", "cuti / percutian"],
    ["，", "", "", ""],
    ["我", "wǒ", "I / me", "saya / aku"],
    ["和", "hé", "and", "dan"],
    ["几名", "jǐ míng", "several / a few", "beberapa orang"],
    ["志同道合", "zhì tóng dào hé", "like-minded", "mempunyai cita-cita dan minat yang sama"],
    ["的", "de", "particle", "yang"],
    ["旅行", "lǚ xíng", "travel / trip", "pelancongan / mengembara"],
    ["同伴", "tóng bàn", "companion / partner", "rakan / teman"],
    ["及", "jí", "and / as well as", "serta / dan"],
    ["一名", "yì míng", "a / one (measure word for person)", "seorang"],
    ["生物学家", "shēng wù xué jiā", "biologist", "ahli biologi"],
    ["向导", "xiàng dǎo", "guide", "pemandu arah"],
    ["，", "", "", ""],
    ["结队", "jié duì", "form a team / group up", "berkumpulan / berpasukan"],
    ["到达", "dào dá", "arrive at / reach", "tiba di / sampai ke"],
    ["南太平洋", "nán tài píng yáng", "South Pacific", "Lautan Pasifik Selatan"],
    ["加拉帕戈斯群岛", "jiā lā pà gē sī qún dǎo", "Galapagos Islands", "Kepulauan Galapagos"],
    ["。", "", "", ""],
    ["在", "zài", "in / at", "di / pada"],
    ["那些", "nà xiē", "those", "itu / yang itu"],
    ["海岛", "hǎi dǎo", "island", "pulau"],
    ["上", "shàng", "on", "atas"],
    ["，", "", "", ""],
    ["有", "yǒu", "there are / have", "ada / mempunyai"],
    ["许多", "xǔ duō", "many", "banyak"],
    ["太平洋", "tài píng yáng", "Pacific", "Pasifik"],
    ["绿龟", "lǜ guī", "green turtle", "penyu hijau"],
    ["孵化", "fū huà", "hatch", "menetas"],
    ["小龟", "xiǎo guī", "baby turtle", "anak penyu"],
    ["的", "de", "particle", "yang"],
    ["巢穴", "cháo xué", "nest / lair", "sarang"],
    ["。", "", "", ""],
    ["我们", "wǒ men", "we / us", "kami / kita"],
    ["到", "dào", "go to / arrive", "pergi ke / sampai"],
    ["那里", "nà lǐ", "there", "sana / di sana"],
    ["就是", "jiù shì", "exactly is / just", "semata-mata / adalah untuk"],
    ["为了", "wèi le", "for the purpose of", "untuk / demi"],
    ["想", "xiǎng", "want to / wish to", "mahu / ingin"],
    ["实地", "shí dì", "on-site / field (observation)", "di tempat kejadian / secara praktikal"],
    ["观察", "guān chá", "observe / watch", "memerhati"],
    ["幼龟", "yòu guī", "baby turtle / hatchling", "anak penyu"],
    ["是", "shì", "is", "adalah"],
    ["怎样", "zěn yàng", "how", "bagaimana"],
    ["离巢", "lí cháo", "leave the nest", "meninggalkan sarang"],
    ["进入", "jìn rù", "enter / go into", "masuk ke / memasuki"],
    ["大海", "dà hǎi", "ocean / sea", "lautan / laut"],
    ["的", "de", "particle", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 2 段

    ["太平洋", "tài píng yáng", "Pacific", "Pasifik"],
    ["绿龟", "lǜ guī", "green turtle", "penyu hijau"],
    ["的", "de", "of", "punya"],
    ["体重", "tǐ zhòng", "body weight", "berat badan"],
    ["大约", "dà yuē", "about / approximately", "kira-kira / lebih kurang"],
    ["一百五十", "yī bǎi wǔ shí", "one hundred and fifty", "seratus lima puluh"],
    ["公斤", "gōng jīn", "kilogram (kg)", "kilogram (kg)"],
    ["，", "", "", ""],
    ["幼龟", "yòu guī", "baby turtle", "anak penyu"],
    ["的", "de", "of", "punya"],
    ["体重", "tǐ zhòng", "body weight", "berat badan"],
    ["则", "zé", "but / on the other hand", "manakala / pula"],
    ["不及", "bù jí", "less than / not up to", "tidak sampai / kurang daripada"],
    ["它的", "tā de", "its", "ia punya"],
    ["百分之一", "bǎi fēn zhī yī", "one percent", "satu peratus"],
    ["。", "", "", ""],
    ["幼龟", "yòu guī", "baby turtle", "anak penyu"],
    ["一般", "yī bān", "generally / usually", "biasanya / umumnya"],
    ["在", "zài", "in / during", "pada / dalam"],
    ["四", "sì", "April (short for 四月)", "April"],
    ["、", "", "", ""],
    ["五月", "wǔ yuè", "May", "Mei"],
    ["间", "jiān", "period / between", "antara / tempoh"],
    ["离巢而出", "lí cháo ér chū", "leave the nest and come out", "keluar meninggalkan sarang"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then / afterwards", "kemudian / lalu"],
    ["争先恐后", "zhēng xiān kǒng hòu", "scrambling to be first", "berebut-rebut / berlumba-lumba"],
    ["地", "de", "particle", "dengan"],
    ["爬向", "pá xiàng", "crawl towards", "merangkak ke arah"],
    ["大海", "dà hǎi", "ocean", "lautan"],
    ["。", "", "", ""],
    ["当然", "dāng rán", "of course / naturally", "sudah tentu / semestinya"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kami"],
    ["都", "dōu", "all", "semua"],
    ["知道", "zhī dào", "know", "tahu / mengetahui"],
    ["，", "", "", ""],
    ["它们", "tā men", "they / them (animals)", "ia / mereka"],
    ["未必", "wèi bì", "not necessarily", "tidak semestinya"],
    ["是", "shì", "are", "adalah"],
    ["安全", "ān quán", "safe", "selamat"],
    ["的", "de", "particle", ""],
    ["。", "", "", ""],
    ["单单", "dān dān", "just / only", "hanya / sekadar"],
    ["从", "cóng", "from", "dari"],
    ["龟巢", "guī cháo", "turtle nest", "sarang penyu"],
    ["去到", "qù dào", "go to", "pergi ke"],
    ["大海", "dà hǎi", "ocean", "lautan"],
    ["就", "jiù", "then / just", "pun / sahaja"],
    ["必须", "bì xū", "must / have to", "mesti / perlu"],
    ["经过", "jīng guò", "pass through / cross", "melalui / merentasi"],
    ["一段", "yí duàn", "a stretch of / a period of", "sepanjang / satu bahagian"],
    ["不短", "bù duǎn", "not short", "bukan pendek / agak jauh"],
    ["的", "de", "particle", "yang"],
    ["沙滩", "shā tān", "sandy beach", "pantai berpasir"],
    ["路程", "lù chéng", "journey / distance", "perjalanan / jarak"],
    ["，", "", "", ""],
    ["而", "ér", "and / but", "dan / manakala"],
    ["幼龟们", "yòu guī men", "baby turtles", "anak-anak penyu"],
    ["只要", "zhǐ yào", "as long as / if only", "asalkan / jika"],
    ["稍不留神", "shāo bù liú shén", "a moment of carelessness", "leka seketika / kurang berhati-hati"],
    ["，", "", "", ""],
    ["便", "biàn", "then / will", "akan / lalu"],
    ["可能", "kě néng", "possibly / maybe", "mungkin"],
    ["成为", "chéng wéi", "become", "menjadi"],
    ["海鸥", "hǎi ōu", "seagull", "burung camar"],
    ["等", "děng", "and so on / etc", "dan lain-lain / seumpamanya"],
    ["食肉鸟", "shí ròu niǎo", "carnivorous bird / bird of prey", "burung pemakan daging / pemangsa"],
    ["的", "de", "particle", "punya"],
    ["食物", "shí wù", "food", "makanan"],
    ["，", "", "", ""],
    ["无法", "wú fǎ", "unable to / no way to", "tidak dapat / mustahil untuk"],
    ["到达", "dào dá", "reach / arrive at", "sampai ke / tiba di"],
    ["大海", "dà hǎi", "ocean", "lautan"],
    ["，", "", "", ""],
    ["继续", "jì xù", "continue", "meneruskan"],
    ["下一步", "xià yí bù", "the next step", "langkah seterusnya"],
    ["的", "de", "particle", "yang"],
    ["生命", "shēng mìng", "life", "nyawa / kehidupan"],
    ["旅程", "lǚ chéng", "journey / voyage", "perjalanan"],
    ["了", "le", "particle", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 3 段

    ["那天", "nà tiān", "that day", "hari itu"],
    ["我们", "wǒ men", "we", "kami"],
    ["来到", "lái dào", "came to / arrived at", "datang ke / tiba di"],
    ["岛上", "dǎo shàng", "on the island", "atas pulau"],
    ["时", "shí", "when", "apabila / ketika"],
    ["，", "", "", ""],
    ["已是", "yǐ shì", "was already", "sudah pun / telah menjadi"],
    ["黄昏", "huáng hūn", "dusk / twilight", "senja"],
    ["，", "", "", ""],
    ["夕阳", "xī yáng", "setting sun", "matahari terbenam"],
    ["也", "yě", "also", "juga"],
    ["快", "kuài", "nearly / fast", "hampir / cepat"],
    ["西下", "xī xià", "setting (sun) / going down", "terbenam / turun ke barat"],
    ["了", "le", "particle", ""],
    ["。", "", "", ""],
    ["积极", "jī jí", "active / enthusiastic / proactive", "bersemangat / proaktif / positif"],
    ["的", "de", "particle", "yang"],
    ["我们", "wǒ men", "we", "kami"],
    ["没有", "méi yǒu", "did not", "tidak"],
    ["怠慢", "dài慢", "slacken / delay / slack off", "lengah / melengah-lengahkan masa"],
    ["，", "", "", ""],
    ["稍", "shāo", "slightly / a bit", "sedikit / seketika"],
    ["休息", "xiū xi", "rest", "berehat"],
    ["片刻", "piàn kè", "a moment / a short while", "sebentar / sekejap"],
    ["，", "", "", ""],
    ["便", "biàn", "then", "lalu / pun"],
    ["开始", "kāi shǐ", "start / begin", "mula / memulakan"],
    ["寻找", "xún zhǎo", "look for / search", "mencari"],
    ["此行", "cǐ xíng", "this trip / journey", "perjalanan ini"],
    ["的", "de", "particle", "punya"],
    ["目标", "mù biāo", "target / objective", "sasaran / matlamat"],
    ["。", "", "", ""],
    ["我们", "wǒ men", "we", "kami"],
    ["分头行事", "fēn tóu xíng shì", "split up and work", "bergerak berasingan / buat kerja haluan masing-masing"],
    ["，", "", "", ""],
    ["很快", "hěn kuài", "very quickly", "dengan sangat cepat / pantas"],
    ["就", "jiù", "then / already", "pun / telah"],
    ["发现", "fā xiàn", "discovered / found", "menemui / menjumpai"],
    ["了", "le", "particle", ""],
    ["一个", "yí gè", "a / one", "sebuah / satu"],
    ["大", "dà", "big / huge", "besar"],
    ["龟巢", "guī cháo", "turtle nest", "sarang penyu"],
    ["。", "", "", ""],
    ["真是", "zhēn shì", "really is", "sungguh / benar-benar"],
    ["振奋人心", "zhèn fèn rén xīn", "inspiring / exciting", "mengujakan / menaikkan semangat"],
    ["，", "", "", ""],
    ["不需要", "bù xū yào", "no need to / do not need", "tidak perlu / tidak usah"],
    ["等待", "děng dài", "wait", "menunggu"],
    ["太久", "tài jiǔ", "too long", "terlalu lama"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kami"],
    ["就", "jiù", "then", "pun / terus"],
    ["看见", "kàn jiàn", "saw / spotted", "nampak / melihat"],
    ["一只", "yì zhī", "a (measure word for animal)", "seekor"],
    ["幼龟", "yòu guī", "baby turtle", "anak penyu"],
    ["率先", "shuài xiān", "take the lead / first", "terlebih dahulu / menjadi yang pertama"],
    ["把", "bǎ", "structural particle", ""],
    ["头", "tóu", "head", "kepala"],
    ["探出", "tàn chū", "poke out / stick out", "menjenguk keluar / mengeluarkan"],
    ["巢穴", "cháo xué", "nest / lair", "sarang"],
    ["巢口", "", "", ""], // 👈 纯文字标点处理
    ["儿", "r", "suffix particle", ""],
    ["，", "", "", ""],
    ["却", "què", "but / however", "tetapi / namun"],
    ["又", "yòu", "yet / again", "pula / lagi"],
    ["欲出而止", "yù chū ér zhǐ", "wanting to go out but stopping", "mahu keluar tetapi terhenti"],
    ["。", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["仿佛", "fǎng fú", "as if / look like", "seolah-olah / seakan-akan"],
    ["在", "zài", "verb particle (-ing)", "sedang"],
    ["侦察", "zhēn chá", "scout / reconnoiter", "meninjau / mengintip"],
    ["看", "kàn", "see / check if", "melihat sama ada"],
    ["外面", "wài mian", "outside", "luar / di luar"],
    ["是否", "shì fǒu", "whether or not", "adakah / sama ada"],
    ["安全", "ān quán", "safe", "selamat"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 4 段

    ["正当", "zhèng dāng", "just as / right when", "ketika / tepat pada saat"],
    ["幼龟", "yòu guī", "baby turtle", "anak penyu"],
    ["踌躇不前", "chóu chú bù qián", "hesitate / hang back", "teragak-agak / terhegeh-hegeh tidak maju"],
    ["时", "shí", "when", "apabila / sewaktu"],
    ["，", "", "", ""],
    ["一只", "yì zhī", "a (measure word for bird)", "seekor"],
    ["嘲鹰", "cháo yīng", "mocking hawk", "burung helang ajuk / mocking hawk"],
    ["从", "cóng", "from", "dari"],
    ["天空中", "tiān kōng zhōng", "in the sky", "ruang angkasa / langit"],
    ["滑下来", "huá xià lái", "glided down / swooped down", "meluncur turun"],
    ["。", "", "", ""],
    ["嘲鹰", "cháo yīng", "mocking hawk", "burung helang ajuk"],
    ["用", "yòng", "use", "menggunakan"],
    ["它的", "tā de", "its", "ia punya"],
    ["尖嘴", "jiān zuǐ", "sharp beak", "paruh tajam"],
    ["猛啄", "měng zhuó", "peck fiercely", "mematuk dengan kuat"],
    ["幼龟", "yòu guī", "baby turtle", "anak penyu"],
    ["的", "de", "particle", "punya"],
    ["头", "tóu", "head", "kepala"],
    ["……", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["企图", "qǐ tú", "attempt / try to", "cuba / cuba untuk / berniat"],
    ["把", "bǎ", "structural particle", ""],
    ["那", "nà", "that", "itu"],
    ["幼龟", "yòu guī", "baby turtle", "anak penyu"],
    ["从", "cóng", "from", "dari"],
    ["巢中", "cháo zhōng", "inside the nest", "dalam sarang"],
    ["拉到", "lā dào", "pull to / drag to", "menarik ke"],
    ["沙滩", "shā tān", "beach", "pantai berpasir"],
    ["上去", "shàng qù", "up there / go up", "ke atas"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段

    ["我", "wǒ", "I", "Saya"],
    ["和", "hé", "and", "dan"],
    ["同伴们", "tóng bàn men", "companions", "rakan-rakan / teman-teman"],
    ["紧张", "jǐn zhāng", "nervously / anxiously", "dengan cemas / gementar"],
    ["地", "de", "particle", ""],
    ["看着", "kàn zhe", "watching", "melihat / menyaksikan"],
    ["眼前", "yǎn qián", "before one's eyes", "di depan mata"],
    ["一幕", "yí mù", "a scene", "satu pemandangan / babak"],
    ["，", "", "", ""],
    ["看见", "kàn jiàn", "seeing", "melihat"],
    ["幼龟", "yòu guī", "baby turtle", "anak penyu"],
    ["危险", "wēi xiǎn", "dangerous", "bahaya / merbahaya"],
    ["的", "de", "particle", "yang"],
    ["处境", "chǔ jìng", "situation / plight", "situasi / keadaan"],
    ["，", "", "", ""],
    ["心", "xīn", "heart", "hati"],
    ["像", "xiàng", "like / as if", "seperti / seolah-olah"],
    ["被人", "bèi rén", "by someone", "oleh orang"],
    ["揪着", "jiū zhe", "gripped / clutched", "dicengkam / ditarik"],
    ["似的", "shì de", "as if", "seolah-olah"],
    ["难受", "nán shòu", "uncomfortable / distressed", "sakit / tidak selesa / pedih"],
    ["。", "", "", ""],
    ["其中", "qí zhōng", "among them", "di antaranya / salah seorang"],
    ["一名", "yì míng", "a (measure word for person)", "seorang"],
    ["朋友", "péng you", "friend", "kawan / rakan"],
    ["焦急", "jiāo jí", "anxiously / worriedly", "dengan cemas / risau"],
    ["地", "de", "particle", ""],
    ["对", "duì", "to / towards", "kepada"],
    ["向导", "xiàng dǎo", "guide", "pemandu arah"],
    ["先生", "xiān sheng", "Mister (Mr.)", "Encik"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你", "nǐ", "you", "Kamu"],
    ["得", "děi", "must / have to", "mesti / perlu"],
    ["想想办法", "xiǎng xiǎng bàn fǎ", "think of a way / do something", "fikirkan jalan / cari ikhtiar"],
    ["啊", "ā", "particle", "lah / ya"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["，", "", "", ""],
    ["then", "rán hòu", "then", "kemudian / lalu"],
    ["转头", "zhuǎn tóu", "turned head around", "memalingkan muka / menoleh"],
    ["再", "zài", "again", "lagi"],
    ["向着", "xiàng zhe", "towards / facing", "menghadap ke arah / kepada"],
    ["我们", "wǒ men", "us", "kami"],
    ["道", "dào", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["还是", "hái sì", "or / had better", "atau / agaknya"],
    ["你们", "nǐ men", "you all", "kamu semua"],
    ["谁", "shéi", "who / anyone", "sesiapa"],
    ["有主意", "yǒu zhǔ yi", "has an idea / plan", "ada idea / cadangan"],
    ["呢", "ne", "particle", "kah"],
    ["？", "", "", ""],
    ["”", "", "", ""],
    ["向导", "xiàng dǎo", "guide", "Pemandu arah"],
    ["先生", "xiān sheng", "Mister", "Encik"],
    ["摊摊手", "tān tān shǒu", "shrugged shoulders / spread hands", "mendepangkan tangan / mengangkat tangan tanda buntu"],
    ["，", "", "", ""],
    ["若无其事", "ruò wú qí shì", "as if nothing had happened / nonchalantly", "seolah-olah tiada apa-apa yang berlaku / bersahaja"],
    ["地", "de", "particle", "dengan"],
    ["答道", "dá dào", "replied", "menjawab"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["叼", "diāo", "peck / carry in mouth", "gonggong / patuk bawa pergi"],
    ["就", "jiù", "then", "pun"],
    ["叼去", "diāo qù", "take away in beak", "bawa pergi"],
    ["吧", "ba", "particle", "lah"],
    ["，", "", "", ""],
    ["这是", "zhè shì", "this is", "ini adalah"],
    ["自然界", "zì rán jiè", "nature / natural world", "alam semula jadi"],
    ["之", "zhī", "of", "punya"],
    ["道", "dào", "way / law", "hukum / jalan"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["旁观", "páng guān", "look on / be onlookers", "tengok sahaja / menjadi pemerhati"],
    ["就", "jiù", "just", "sahaja"],
    ["好", "hǎo", "good / fine", "baik / memadai"],
    ["了", "le", "particle", ""],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["富有", "fù yǒu", "full of / rich in", "kaya dengan / penuh dengan"],
    ["同情心", "tóng qíng xīn", "sympathy / compassion", "sifat simpati / belas kasihan"],
    ["的", "de", "particle", "yang"],
    ["朋友", "péng you", "friend", "kawan"],
    ["气急败坏", "qì jí bài huài", "flustered / exasperated", "marah-marah / meradang / keluh-kesah"],
    ["，", "", "", ""],
    ["可", "kě", "but", "tetapi / namun"],
    ["也", "yě", "also", "juga"],
    ["无可奈何", "wú kě nài hé", "have no alternative / helpless", "tidak dapat berbuat apa-apa / buntu"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 6 段

    ["虽然", "suī rán", "although", "Walaupun"],
    ["如此", "rú cǐ", "so / like this", "begitu / demikian"],
    ["，", "", "", ""],
    ["向导", "xiàng dǎo", "guide", "pemandu arah"],
    ["先生", "xiān sheng", "Mister", "Encik"],
    ["的", "de", "of", "punya"],
    ["冷淡", "lěng dàn", "indifference / coldness", "sikap dingin / acuh tak acuh"],
    ["，", "", "", ""],
    ["引起", "yǐn qǐ", "caused / sparked", "mencetuskan / menimbulkan"],
    ["了", "le", "particle", ""],
    ["一行人", "yì xíng rén", "the group of travelers", "kumpulan orang itu / kami semua"],
    ["对", "duì", "towards", "terhadap"],
    ["他", "tā", "him", "dia"],
    ["“", "", "", ""],
    ["见死不救", "jiàn sǐ bú jiù", "refuse to help in a crisis", "melihat orang susah tanpa membantu / lepas tangan"],
    ["”", "", "", ""],
    ["的", "de", "particle", "yang"],
    ["议论", "yì lùn", "discussion / criticism", "bincangan / rungutan / ulasan"],
    ["和", "hé", "and", "dan"],
    ["抗议", "kàng yì", "protest", "bantahan"],
    ["。", "", "", ""],
    ["在", "zài", "under", "dalam keadaan / di bawah"],
    ["不情愿", "bù qíng yuàn", "unwilling", "tidak rela / berat hati"],
    ["和", "hé", "and", "dan"],
    ["被", "bèi", "by (passive particle)", "di- / oleh"],
    ["众人", "zhòng rén", "everyone / the crowd", "orang ramai / semua orang"],
    ["施压", "shī yā", "exert pressure on", "diberi tekanan / didesak"],
    ["的", "de", "particle", "yang"],
    ["情况", "qíng kuàng", "situation / circumstance", "keadaan / situasi"],
    ["之下", "zhī xià", "under", "di bawah"],
    ["，", "", "", ""],
    ["向导", "xiàng dǎo", "guide", "pemandu arah"],
    ["先生", "xiān sheng", "Mister", "Encik"],
    ["只好", "zhǐ hǎo", "have no choice but to", "terpaksa / mahu tidak mahu"],
    ["充当", "chōng dāng", "act as / serve as", "menjadi / berperanan sebagai"],
    ["英雄", "yīng xióng", "hero", "wira / penyelamat"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["飞奔", "fēi bēn", "dashed / ran like the wind", "berlari pantas / meluru"],
    ["过去", "guò qù", "over / go over", "ke sana"],
    ["抱起", "bào qǐ", "picked up / scooped up", "mengangkat / mendakap up"],
    ["幼龟", "yòu guī", "baby turtle", "anak penyu"],
    ["，", "", "", ""],
    ["并", "bìng", "and", "serta / dan"],
    ["把它", "bǎ tā", "it (structural object)", "membawanya / ia"],
    ["引向", "yǐn xiàng", "lead towards", "membimbing ke arah / menghala ke"],
    ["大海", "dà hǎi", "ocean", "lautan"],
    ["……", "", "", ""],
    ["那只", "nà zhī", "that (animal)", "seekor / yang itu"],
    ["嘲鹰", "cháo yīng", "mocking hawk", "burung helang ajuk"],
    ["眼睁睁", "yǎn zhēng zhēng", "looking on helplessly", "melihat sahaja dengan mata terbeliak"],
    ["看着", "kàn zhe", "watching", "menyaksikan / melihat"],
    ["快", "kuài", "almost", "hampir"],
    ["到手", "dào shǒu", "obtained / within grasp", "ke tangan / dapat"],
    ["的", "de", "particle", "yang"],
    ["美食", "měi shí", "delicious food / prey", "makanan lazat / mangsa"],
    ["没有", "méi yǒu", "gone / did not have", "tiada / terlepas"],
    ["了", "le", "particle", ""],
    ["，", "", "", ""],
    ["只能", "zhǐ néng", "could only", "hanya boleh"],
    ["颓丧", "tuí sàng", "dejectedly / crestfallen", "dengan hampa / kecewa / lemah semangat"],
    ["地", "de", "particle", "dengan"],
    ["飞走了", "fēi zǒu le", "flew away", "terbang pergi"],
    ["。", "", "", ""],
    ["我们", "wǒ men", "we", "Kami"],
    ["看见", "kàn jiàn", "saw", "melihat"],
    ["幼龟", "yòu guī", "baby turtle", "anak penyu"],
    ["脱离险境", "tuō lí xiǎn jìng", "out of danger / escape hazard", "terlepas daripada bahaya"],
    ["，", "", "", ""],
    ["还", "hái", "also / and furthermore", "malah / dan juga"],
    ["顺利", "shùn lì", "smoothly / successfully", "dengan lancar"],
    ["到达", "dào dá", "reach / arrive", "sampai ke"],
    ["大海", "dà hǎi", "ocean", "lautan"],
    ["，", "", "", ""],
    ["大家", "dà jiā", "everyone", "semua orang"],
    ["都", "dōu", "all", "pun"],
    ["松了一口气", "sōng le yì kǒu qì", "heaved a sigh of relief", "menarik nafas lega"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 7 段

    ["然而", "rán ér", "however / yet", "Namun / bagaimanapun"],
    ["，", "", "", ""],
    ["紧接着", "jǐn jiē zhe", "immediately after", "sejurus selepas itu"],
    ["发生", "fā shēng", "happened / occurred", "berlaku"],
    ["的", "de", "particle", "yang"],
    ["事情", "shì qing", "matter / incident", "perkara / peristiwa"],
    ["却", "què", "however / surprisingly", "sebaliknya / pula"],
    ["令", "lìng", "make / cause", "membuatkan / menyebabkan"],
    ["大家", "dà jiā", "everyone", "semua orang"],
    ["极为", "jí wéi", "extremely", "amat / sangat"],
    ["震惊", "zhèn jīng", "shocked / astounded", "terkejut / tergempar"],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["永远永远", "yǒng yuǎn yǒng yuǎn", "forever and ever", "selama-lamanya / sampai bila-bila"],
    ["都", "dōu", "all / emphasis", "pun"],
    ["忘不了", "wàng bù liǎo", "cannot forget", "tidak dapat melupakan"],
    ["……", "", "", ""],

    ["\n", "", "", ""], // 👈 第 8 段

    ["在", "zài", "after / at", "Selepas / ketika"],
    ["向导", "xiàng dǎo", "guide", "pemandu arah"],
    ["先生", "xiān sheng", "Mister", "Encik"],
    ["抱走", "bào zǒu", "carried away", "membawa pergi / mengangkat"],
    ["幼龟", "yòu guī", "baby turtle", "anak penyu"],
    ["不久", "bù jiǔ", "not long", "tidak lama"],
    ["后", "hòu", "after", "selepas"],
    ["，", "", "", ""],
    ["成群", "chéng qún", "in groups / swarms", "berkumpulan / berkawan-kawan"],
    ["的", "de", "particle", "yang"],
    ["幼龟", "yòu guī", "baby turtles", "anak penyu"],
    ["即", "jí", "then / immediately", "terus / segera"],
    ["从", "cóng", "from", "dari"],
    ["巢口", "cháo kǒu", "nest entrance", "mulut sarang"],
    ["鱼贯而出", "yú guàn ér chū", "come out in single file / stream out", "keluar berduyung-duyung / beriringan"],
    ["。", "", "", ""],
    ["它们", "tā men", "they (animals)", "Ia / mereka"],
    ["正", "zhèng", "are currently", "sedang"],
    ["扭扭摆摆", "niǔ niǔ bǎi bǎi", "waddling / swaying", "terhegeh-hegeh / terhuyung-hayang / melenggang-lenggok"],
    ["地", "de", "particle", "dengan"],
    ["朝", "cháo", "towards", "ke arah"],
    ["大海", "dà hǎi", "ocean", "lautan"],
    ["爬去", "pá qù", "crawl towards", "merangkak pergi"],
    ["！", "", "", ""],
    ["事实", "shì shí", "fact / reality", "Hakikat / kenyataan"],
    ["很快", "hěn kuài", "very quickly", "dengan cepat"],
    ["使", "shǐ", "make / cause", "membuatkan / menyebabkan"],
    ["我们", "wǒ men", "us", "kami"],
    ["明白", "míng bai", "understand / realize", "faham / sedar"],
    ["：", "", "", ""],
    ["我们", "wǒ men", "we", "kami"],
    ["原来", "yuán lái", "actually / turn out to be", "rupa-rupanya / sebenarnya"],
    ["干了", "gàn le", "did / committed", "telah melakukan"],
    ["一件", "yí jiàn", "a (measure word for matter)", "satu"],
    ["愚不可及", "yú bù kě jí", "unbelievably stupid / foolish in the extreme", "amat bodoh / kebodohan yang melampau"],
    ["的", "de", "particle", "yang"],
    ["蠢事", "chǔn shì", "foolish thing / blunder", "perkara bodoh"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第 9 段

    ["那只", "nà zhī", "that (animal)", "Seekor / yang itu"],
    ["先", "xiān", "first", "terlebih dahulu / mula-mula"],
    ["出来", "chū lái", "come out", "keluar"],
    ["的", "de", "particle", "yang"],
    ["幼龟", "yòu guī", "baby turtle", "anak penyu"],
    ["，", "", "", ""],
    ["原来", "yuán lái", "actually / turn out to be", "rupa-rupanya / asalnya"],
    ["是", "shì", "was", "adalah"],
    ["幼龟群", "yòu guī qún", "the group of baby turtles", "kumpulan anak penyu"],
    ["的", "de", "of", "punya"],
    ["“", "", "", ""],
    ["侦察兵", "zhēn chá bīng", "scout / recon soldier", "peninjau / pengintip"],
    ["”", "", "", ""],
    ["，", "", "", ""],
    ["一旦", "yí dàn", "once / as soon as", "sekiranya / sebaik sahaja"],
    ["遇到", "yù dào", "encounter / run into", "menghadapi / terserempak"],
    ["危险", "wēi xiǎn", "danger", "bahaya"],
    ["，", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["便", "biàn", "then", "akan / lalu"],
    ["会", "huì", "will", "akan"],
    ["返回", "fǎn huí", "return to / go back", "kembali ke / pulang ke"],
    ["龟巢", "guī cháo", "turtle nest", "sarang penyu"],
    ["。", "", "", ""],
    ["它们", "tā men", "they (animals)", "Mereka / ia"],
    ["将会", "jiāng huì", "will", "akan"],
    ["再", "zài", "again / further", "lagi / kemudian"],
    ["静待", "jìng dài", "wait quietly", "menunggu dengan senyap / tenang"],
    ["适当", "shì dàng", "appropriate / suitable", "sesuai / sepatutnya"],
    ["的", "de", "particle", "yang"],
    ["时机", "shí jī", "opportunity / timing", "masa / peluang / saat"],
    ["，", "", "", ""],
    ["才", "cái", "only then", "baru / barulah"],
    ["再", "zài", "again", "sekali lagi"],
    ["离巢", "lí cháo", "leave nest", "meninggalkan sarang"],
    ["回归", "huí guī", "return to", "kembali ke"],
    ["大海", "dà hǎi", "ocean", "lautan"],
    ["。", "", "", ""],
    ["现在", "xiàn zài", "now", "Sekarang"],
    ["幼龟", "yòu guī", "baby turtle", "anak penyu"],
    ["被", "bèi", "by (passive particle)", "telah / di-"],
    ["向导", "xiàng dǎo", "guide", "pemandu arah"],
    ["先生", "xiān sheng", "Mister", "Encik"],
    ["蓄意", "xù yì", "deliberately / intentionally", "sengaja / dengan sengaja"],
    ["引向", "yǐn xiàng", "led towards", "dihala ke / dibawa ke arah"],
    ["大海", "dà hǎi", "ocean", "lautan"],
    ["，", "", "", ""],
    ["巢中", "cháo zhōng", "inside the nest", "di dalam sarang"],
    ["的", "de", "particle", "yang"],
    ["幼龟", "yòu guī", "baby turtles", "anak penyu"],
    ["得到", "dé dào", "received / got", "mendapat / menerima"],
    ["错误", "cuò wù", "wrong / incorrect", "salah / silap"],
    ["信息", "xìn xī", "information / message", "maklumat / mesej"],
    ["，", "", "", ""],
    ["以为", "yǐ wéi", "thought / assumed", "menyangka / mengira"],
    ["外面", "wài mian", "outside", "luar / keadaan luar"],
    ["的", "de", "particle", "yang"],
    ["环境", "huán jìng", "environment / surroundings", "persekitaran / keadaan"],
    ["很", "hěn", "very", "sangat / amat"],
    ["安全", "ān quán", "safe", "selamat"],
    ["，", "", "", ""],
    ["于是", "yú shì", "so / therefore", "maka / oleh itu"],
    ["争先恐后", "zhēng xiān kǒng hòu", "scrambling to be first", "berebut-rebut"],
    ["地", "de", "particle", "dengan"],
    ["倾巢而出", "qīng cháo ér chū", "pour out thoroughly / empty the nest", "keluar beramai-ramai / keluar semuanya"],
    ["，", "", "", ""],
    ["迫不及待", "pò bù jí dài", "impatient / cannot wait", "tidak sabar-sabar / tergesa-gesa"],
    ["往外", "wǎng wài", "outwards", "ke luar"],
    ["爬", "pá", "crawl", "merangkak"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 10 段

    ["已达", "yǐ dá", "had already reached", "Sudah mencapai / telah sampai"],
    ["黄昏", "huáng hūn", "dusk / evening", "senja"],
    ["的", "de", "particle", "yang"],
    ["海岛", "hǎi dǎo", "island", "pulau"],
    ["，", "", "", ""],
    ["阳光", "yáng guāng", "sunlight", "cahaya matahari"],
    ["仍然", "réng rán", "still", "masih"],
    ["很", "hěn", "very", "sangat"],
    ["明媚", "míng mèi", "bright and beautiful", "cerah / indah"],
    ["。", "", "", ""],
    ["从", "cóng", "from", "Dari"],
    ["龟巢", "guī cháo", "turtle nest", "sarang penyu"],
    ["到", "dào", "to", "ke"],
    ["海边", "hǎi biān", "seashore / beach", "tepi pantai"],
    ["的", "de", "particle", "yang"],
    ["一大段", "yí dà duàn", "a large stretch of", "satu bahagian panjang"],
    ["沙滩", "shā tān", "beach", "pantai berpasir"],
    ["路程", "lù chéng", "distance / route", "perjalanan"],
    ["，", "", "", ""],
    ["全然是", "quán rán shì", "completely was", "sepenuhnya adalah / langsung"],
    ["无遮无挡", "wú zhē wú dǎng", "completely unsheltered / open", "tanpa perlindungan / terdedah luas"],
    ["。", "", "", ""],
    ["成百上千", "chéng bǎi shàng qiān", "hundreds and thousands", "beratus-ratus dan beribu-ribu"],
    ["的", "de", "particle", "yang"],
    ["幼龟", "yòu guī", "baby turtles", "anak penyu"],
    ["结群而出", "jié qún ér chū", "emerge in large groups", "keluar berkawan-kawan / berkumpulan"],
    ["，", "", "", ""],
    ["很快", "hěn kuài", "very quickly", "dengan sangat cepat"],
    ["引来", "yǐn lái", "attracted / drew in", "menarik kehadiran / mengundang"],
    ["许多", "xǔ duō", "many", "banyak"],
    ["食肉鸟", "shí ròu niǎo", "carnivorous birds", "burung pemangsa / pemakan daging"],
    ["，", "", "", ""],
    ["这回", "zhè huí", "this time", "kali ini"],
    ["它们", "tā men", "they (birds)", "mereka / burung-burung itu"],
    ["确实", "què shí", "indeed / truly", "memang / sememangnya"],
    ["不费吹灰之力", "bú fèi chuī huī zhī lì", "without the slightest effort / effortless", "tanpa sebarang usaha / dengan tersangat mudah"],
    ["，", "", "", ""],
    ["就可以", "jiù kě yǐ", "then can / able to", "sudah boleh / dapat"],
    ["饱餐一顿", "bǎo cān yí dùn", "enjoy a hearty meal", "makan dengan sekenyang-kenyangnya / berpesta makan"],
    ["了", "le", "particle", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 11 段

    ["“", "", "", ""],
    ["我的天啊", "wǒ de tiān ā", "Oh my god / My goodness", "Oh Tuhanku"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["听见", "tīng jiàn", "heard", "mendengar"],
    ["背后", "bèi hòu", "behind / at the back", "di belakang"],
    ["有人", "yǒu rén", "someone", "ada orang"],
    ["说", "shuō", "said", "berkata"],
    ["，", "", "", ""],
    ["“", "", "", ""],
    ["看", "kàn", "look / see", "tengok / lihat"],
    ["我们", "wǒ men", "we", "kita"],
    ["做了", "zuò le", "did", "telah lakukan"],
    ["什么", "shén me", "what", "apa"],
    ["蠢事", "chǔn shì", "foolish thing", "perkara bodoh"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 12 段

    ["说时迟，那时快", "shuō shí chí, nà shí kuài", "no sooner said than done / in a flash", "dalam sekelip mata / dengan pantasnya"],
    ["，", "", "", ""],
    ["一只", "yì zhī", "one (animal)", "seekor"],
    ["、", "", "", ""],
    ["两只", "liǎng zhī", "two", "dua ekor"],
    ["、", "", "", ""],
    ["三只", "sān zhī", "three", "tiga ekor"],
    ["……", "", "", ""],
    ["幼龟", "yòu guī", "baby turtles", "anak penyu"],
    ["已成了", "yǐ chéng le", "had already become", "telah menjadi"],
    ["嘲鹰", "cháo yīng", "mocking hawks", "burung helang ajuk"],
    ["、", "", "", ""],
    ["海鸥", "hǎi ōu", "seagulls", "burung camar"],
    ["、", "", "", ""],
    ["鲣鸟", "jiān niǎo", "boobies (type of bird)", "burung dendang laut / booby"],
    ["的", "de", "particle", "yang"],
    ["腹中", "fù zhōng", "inside stomach", "dalam perut"],
    ["食物", "shí wù", "food", "makanan"],
    ["。", "", "", ""],
    ["我们的", "wǒ men de", "our", "Kami punya"],
    ["向导", "xiàng dǎo", "guide", "pemandu arah"],
    ["先生", "xiān sheng", "Mister", "Encik"],
    ["临危不乱", "lín wēi bú luàn", "stay calm in the face of crisis", "tenang menghadapi bahaya / tidak panik dalam krisis"],
    ["，", "", "", ""],
    ["顾不得", "gù bù dé", "cannot care for / ignore", "tidak sempat menghiraukan / tidak peduli lagi"],
    ["看戏", "kàn xì", "watching the drama", "menonton sahaja / melihat babak itu"],
    ["、", "", "", ""],
    ["顾不得", "gù bù dé", "cannot care for", "tidak peduli tentang"],
    ["自身", "zì shēn", "oneself", "diri sendiri"],
    ["，", "", "", ""],
    ["赶紧", "gǎn jǐn", "hurriedly / quickly", "segera / dengan cepat"],
    ["脱下", "tuō xià", "take off (clothing/hat)", "menanggalkan / membuka"],
    ["头上", "tóu shàng", "on the head", "atas kepala"],
    ["的", "de", "particle", "punya"],
    ["棒球帽", "bàng qiú mào", "baseball cap", "topi besbol"],
    ["，", "", "", ""],
    ["迅速", "xùn sù", "rapidly / swiftly", "dengan pantas / laju"],
    ["抓起", "zhuā qǐ", "grabbed / scooped up", "menangkap / merenggut up"],
    ["十几只", "shǐ jǐ zhī", "more than a dozen / a dozen or so", "belasan ekor / lebih sepuluh ekor"],
    ["幼龟", "yòu guī", "baby turtles", "anak penyu"],
    ["，", "", "", ""],
    ["放进", "fàng jìn", "put into", "memasukkan ke dalam"],
    ["帽中", "mào zhōng", "inside the cap", "dalam topi"],
    ["，", "", "", ""],
    ["向", "xiàng", "towards", "ke arah"],
    ["大海", "dà hǎi", "ocean", "lautan"],
    ["的", "de", "particle", "yang"],
    ["方向", "fāng xiàng", "direction", "arah"],
    ["奔去", "bēn qù", "ran towards", "berlari menuju ke"],
    ["。", "", "", ""],
    ["我们", "wǒ men", "we", "Kami"],
    ["也", "yě", "also", "juga"],
    ["有样学样", "yǒu yàng xué yàng", "follow suit / copy what others do", "meniru perbuatan tersebut / mengikut contoh"],
    ["，", "", "", ""],
    ["什么", "shén me", "anything / whatever", "apa-apa pun"],
    ["也", "yě", "also", "pun"],
    ["顾不得", "gù bù dé", "could not care for", "tidak dihiraukan lagi"],
    ["了", "le", "particle", ""],
    ["，", "", "", ""],
    ["身上", "shēn shàng", "on the body", "pada badan / apa yang ada di badan"],
    ["有什么", "yǒu shén me", "have whatever", "ada apa sahaja"],
    ["就", "jiù", "then", "terus"],
    ["用", "yòng", "use", "gunakan"],
    ["什么", "shén me", "what / whatever", "apa yang ada"],
    ["，", "", "", ""],
    ["就这样", "jiù zhè yàng", "just like this", "begitulah / dengan cara begini"],
    ["地", "de", "particle", ""],
    ["在", "zài", "on", "di atas"],
    ["沙滩", "shā tān", "beach", "pantai berpasir"],
    ["上", "shàng", "on", "atas"],
    ["疲于奔命", "pí yú bēn mìng", "tired out from running around / exhausted", "keletihan ke sana kemari / berlari bermati-matian"],
    ["，", "", "", ""],
    ["算是", "suàn shì", "be considered as", "dikira sebagai / boleh dianggap"],
    ["对", "duì", "towards / for", "terhadap / atas"],
    ["自己", "zì jǐ", "one's own", "diri sendiri punya"],
    ["的", "de", "particle", ""],
    ["过错", "guò cuò", "fault / mistake / blunder", "kesilapan / kesalahan"],
    ["做", "zuò", "do / make", "melakukan / membuat"],
    ["一些", "yì xiē", "some", "sedikit / beberapa"],
    ["补救", "bǔ jiù", "remedy / salvage", "pembetulan / tebus salah"],
    ["，", "", "", ""],
    ["略尽绵力", "lüè jìn mián lì", "do what little one can / contribute one's humble effort", "menyumbang sedikit usaha yang termampu"],
    ["吧", "ba", "particle", "lah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 13 段

    ["时间", "shí jiān", "time", "Masa"],
    ["一分一秒", "yì fēn yì miǎo", "minute by minute, second by second", "seminit demi seminit, sesaat demi sesaat"],
    ["地", "de", "particle", ""],
    ["过去了", "guò qù le", "passed by", "telah berlalu"],
    ["，", "", "", ""],
    ["几十只", "jǐ shí zhī", "dozens of", "berpuluh-puluh ekor"],
    ["食肉鸟", "shí ròu niǎo", "carnivorous birds", "burung pemangsa"],
    ["吃得", "chī de", "ate (with description)", "makan sampai"],
    ["饱饱的", "bǎo bǎo de", "very full", "sangat kenyang"],
    ["，", "", "", ""],
    ["发出", "fā chū", "emitted / made", "mengeluarkan"],
    ["欢愉", "huān yú", "joyful / cheerful", "kegembiraan / kepuasan yang riang"],
    ["满足", "mǎn zú", "satisfied", "puas / kepuasan"],
    ["的", "de", "particle", "yang"],
    ["鸣叫声", "míng jiào shēng", "chirping / crying sound of birds", "bunyi kicauan / jeritan burung"],
    ["后", "hòu", "after", "selepas"],
    ["，", "", "", ""],
    ["呼啸而去", "hū xiào ér qù", "whistled away / rushed away with a whistle", "terbang pergi dengan hinggar-binggar / menderu pergi"],
    ["。", "", "", ""],
    ["它们", "tā men", "their (birds)", "Mereka punya"],
    ["响彻云霄", "xiǎng chè yún xiāo", "resounding through the skies / echoing up to the clouds", "bergema membelah awan / sangat lantang"],
    ["的", "de", "particle", "yang"],
    ["鸣叫声", "míng jiào shēng", "crying sound", "bunyi jeritan / kicauan"],
    ["听在", "tīng zài", "heard in", "terdengar pada"],
    ["我们的", "wǒ men de", "our", "kami punya"],
    ["耳里", "ěr lǐ", "ears", "telinga / dalam telinga"],
    ["，", "", "", ""],
    ["却是", "què shì", "however was", "namun adalah / sebaliknya pula"],
    ["那么地", "nà me de", "so / that much", "begitu sekali"],
    ["刺耳", "cì ěr", "harsh / grating on ears", "menyakitkan telinga / bingit"],
    ["。", "", "", ""],
    ["还有", "hái yǒu", "still have / also", "Masih ada"],
    ["一只", "yì zhī", "one (bird)", "seekor"],
    ["鹰", "yīng", "hawk / eagle", "helang"],
    ["仍", "réng", "still", "masih"],
    ["静静", "jìng jìng", "quietly", "senyap-senyap / dengan tenang"],
    ["地", "de", "particle", ""],
    ["伫立", "zhù lì", "stand for a long time", "berdiri tegak / kaku"],
    ["在", "zài", "on", "di atas"],
    ["沙滩", "shā tān", "beach", "pantai berpasir"],
    ["上", "shàng", "on", "atas"],
    ["，", "", "", ""],
    ["希望", "xī wàng", "hope / look forward to", "berharap / berharap agar"],
    ["能", "néng", "can", "dapat / boleh"],
    ["捕捉到", "bǔ zhuō dào", "catch / capture", "menangkap / menyambar"],
    ["最后", "zuì hòu", "the last", "yang terakhir"],
    ["一只", "yì zhī", "one", "seekor"],
    ["迷路", "mí lù", "lost (way)", "sesat / hilang arah"],
    ["的", "de", "particle", "yang"],
    ["幼龟", "yòu guī", "baby turtle", "anak penyu"],
    ["作", "zuò", "as / to be", "sebagai"],
    ["佳肴", "jiā yáo", "delicacy / fine food", "makanan lazat / hidangan enak"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 14 段

    ["我", "wǒ", "I", "Saya"],
    ["和", "hé", "and", "dan"],
    ["同伴们", "tóng bàn men", "companions", "rakan-rakan"],
    ["像", "xiàng", "like / as if", "seperti"],
    ["做错事", "zuò cuò shì", "did something wrong", "buat salah / melakukan kesilapan"],
    ["的", "de", "particle", "yang"],
    ["小孩", "xiǎo hái", "child", "budak-budak / anak kecil"],
    ["儿", "r", "suffix particle", ""],
    ["低垂着头", "dī chuí zhe tóu", "hanging head low", "menundukkan kepala"],
    ["，", "", "", ""],
    ["在", "zài", "on", "di atas"],
    ["沙滩", "shā tān", "beach", "pantai berpasir"],
    ["上", "shàng", "on", "atas"],
    ["慢慢", "màn màn", "slowly", "perlahan-lahan"],
    ["前进", "qián jìn", "advance / move forward", "melangkah maju / berjalan ke depan"],
    ["。", "", "", ""],
    ["似乎", "sì hū", "seemingly / as if", "Seakan-akan / nampaknya"],
    ["在", "zài", "among / in", "dalam kalangan / di"],
    ["这群", "zhè qún", "this group of", "kumpulan ini"],
    ["凡人", "fán rén", "mortal / ordinary people", "manusia biasa"],
    ["中间", "zhōng jiān", "among / middle", "antara / tengah"],
    ["，", "", "", ""],
    ["一切", "yí qiè", "everything", "segala-galanya / semua perkara"],
    ["都", "dōu", "all", "pun"],
    ["寂然", "jì rán", "quietly / silently", "sunyi sepi"],
    ["静止", "jìng zhǐ", "still / static", "terhenti / kaku"],
    ["了", "le", "particle", ""],
    ["。", "", "", ""],
    ["终于", "zhōng yú", "finally", "Akhirnya"],
    ["，", "", "", ""],
    ["向导", "xiàng dǎo", "guide", "pemandu arah"],
    ["先生", "xiān sheng", "Mister", "Encik"],
    ["感慨", "gǎn kǎi", "with deep emotion / sigh with regret", "dengan penuh kesal / mengeluh emosi"],
    ["地", "de", "particle", ""],
    ["发出", "fā chū", "uttered / let out", "mengeluarkan / melepaskan"],
    ["了", "le", "particle", ""],
    ["悲叹", "bēi tàn", "sigh / lament", "keluhan sedih / rintihan"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["如果", "rú guǒ", "if", "Jika / kalau"],
    ["不是", "bú shì", "not / wasn't for", "bukan kerana"],
    ["我们", "wǒ men", "we", "kita / kami"],
    ["人类", "rén lèi", "humans / mankind", "umat manusia"],
    ["，", "", "", ""],
    ["这些", "zhè xiē", "these", "penyu-penyu ini / semua ini"],
    ["海龟", "hǎi guī", "sea turtles", "penyu"],
    ["根本", "gēn běn", "at all / simply", "sama sekali / langsung"],
    ["就", "jiù", "then", "pun"],
    ["不会", "bú huì", "will not", "tidak akan"],
    ["受到", "shòu dào", "receive / suffer", "menerima / mengalami"],
    ["伤害", "shāng hài", "harm / injury", "kecederaan / kemudaratan / kebinasaan"],
    ["。", "", "", ""],
    ["”", "", "", ""], // 👈 完美并入下引号

    ["\n", "", "", ""], // 👈 第 15 段

    ["人", "rén", "Humans / people", "Manusia"],
    ["啊", "ā", "particle", "lah / ya"],
    ["，", "", "", ""],
    ["万物之灵", "wàn wù zhī líng", "the soul of all matter / crown of creation", "makhluk paling mulia antara hidupan / ketua segala makhluk"],
    ["。", "", "", ""],
    ["然而", "rán ér", "however", "Namun / akan tetapi"],
    ["，", "", "", ""],
    ["当", "dāng", "when", "apabila / tatkala"],
    ["这", "zhè", "this", "ini"],
    ["万物之灵", "wàn wù zhī líng", "crown of creation", "makhluk paling mulia"],
    ["自作聪明", "zì zuò cōng míng", "smart-aleck / think oneself clever", "memandai-mandai / merasa diri bijak"],
    ["时", "shí", "when", "ketika / sewaktu"],
    ["，", "", "", ""],
    ["一切", "yí qiè", "everything", "segala-galanya"],
    ["都", "dōu", "all", "pun"],
    ["有可能", "yǒu kě néng", "has the possibility to / likely", "mungkin / ada kemungkinan"],
    ["走向", "zǒu xiàng", "move towards / head into", "menuju ke arah / menjadi"],
    ["反面", "fǎn miàn", "the opposite side / reverse", "sebaliknya / kesan buruk"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 分段标记，切入文末作者出处

    // 文末作者出处
    ["（", "", "", ""],
    ["伯罗蒙塞尔", "bó luó méng sài ěr", "Bromhall (Author)", "Bromhall (Penulis)"],
    ["《", "", "", ""],
    ["大自然的秘密", "dà zì rán de mì mì", "The Secret of Nature", "Rahsia Alam Semula Jadi"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with / has", "ada"],
    ["改动", "gǎi dòng", "adaptations / modifications", "perubahan / ubah suai"],
    ["）", "", "", ""]
];
